import Head from 'next/head'
import styles from '../styles/Home.module.css';
import Nav from '../components/Nav';
import Image from 'next/image';
import background from '../public/background.jpg'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Efarmogi Computers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
     
        <div className={styles.background}>
          <Image src={background} alt="background image" layout="fill" objectFit="cover" />
          <div className={styles.heroText}><h1 className={styles.mainHeading}>Δειτε Τις Υπηρεσιες Μας!</h1></div>
        </div>
        
      </main>
      
    </div>
  )
}
